"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { generatePrepSheet } from "@/server/actions";

export default function PrepSheetView({ content }: { content: string }) {
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<{ keyFacts: string[]; ambiguities: string[]; questionsToAsk: string[] } | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await generatePrepSheet(content);
      setData(result);
    } catch (e: any) {
      console.error(e);
      setError(e.message || "An error occurred generating the prep sheet.");
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle>Attorney Consultation Prep Sheet</CardTitle>
        <div className="flex gap-2">
          {data && <Button variant="outline" onClick={handlePrint}>Print / Save PDF</Button>}
          <Button onClick={handleGenerate} disabled={loading || !content}>
            {loading ? "Generating..." : "Generate Prep Sheet"}
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-6" aria-live="polite" aria-busy={loading}>
        {error && (
          <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-md text-red-500 text-sm">
            <strong className="font-semibold">Error:</strong> {error}
          </div>
        )}
        {data && (
          <div className="print:block space-y-6 p-6 border rounded-lg bg-white">
            <div className="border-b pb-4">
              <h2 className="text-2xl font-bold text-slate-900">Attorney Consultation Checklist</h2>
              <p className="text-sm text-slate-500 mt-1">Generated by Aequitas AI based on your provided document.</p>
            </div>
            
            <section>
              <h3 className="text-lg font-semibold text-slate-800 border-b pb-2 mb-3">1. Key Facts Extracted</h3>
              <ul className="list-disc pl-5 space-y-1 text-slate-700">
                {data.keyFacts.map((fact, i) => <li key={i}>{fact}</li>)}
              </ul>
            </section>

            <section>
              <h3 className="text-lg font-semibold text-slate-800 border-b pb-2 mb-3">2. Ambiguities & Missing Terms</h3>
              <ul className="list-disc pl-5 space-y-1 text-slate-700">
                {data.ambiguities.map((amb, i) => <li key={i}>{amb}</li>)}
              </ul>
            </section>

            <section>
              <h3 className="text-lg font-semibold text-slate-800 border-b pb-2 mb-3">3. Tactical Questions to Ask Your Lawyer</h3>
              <ul className="list-decimal pl-5 space-y-3 text-slate-700">
                {data.questionsToAsk.map((q, i) => (
                  <li key={i} className="font-medium">
                    {q}
                    <div className="mt-2 h-16 border rounded bg-slate-50 w-full print:border-slate-300 print:bg-transparent"></div>
                  </li>
                ))}
              </ul>
            </section>

            <div className="mt-8 pt-4 border-t text-xs text-slate-500 text-center">
              Disclaimer: This sheet does not constitute legal advice. It is a preparation tool designed to make your consultation more efficient and focused.
            </div>
          </div>
        )}
        {!data && !loading && (
          <p className="text-slate-500 text-center py-8">Click the button to generate a targeted checklist for an attorney consultation.</p>
        )}
      </CardContent>
    </Card>
  );
}
